### ISSUE TITLE
app-catalog: Add offical, verified, CNCF badges to the apps

### ISSUE THREAD

**Issue by joaquimrocha** [headlamp-k8s/plugins#20]
Our apps come from ArtifactHub and they have the concept of being official, verified, and a CNCF project.
We should make these clear in our app catalog as well, since these are important characteristics that help users opt for installing certain packages and it's also related to security (by making sure e.g. that an app being installed is a verified app by its owner).

**Comment by illume** [comment]
I assume this can be closed now, because this was merged:
- #42

With this change:
>  Added support for displaying ArtifactHub badges (official, verified, and CNCF project) in the app catalog.
