### ISSUE TITLE
prometheus: Add pvc metrics

### ISSUE THREAD

**Issue by farodin91** [headlamp-k8s/plugins#25]
It would be great to have metrics on PVCs.

Some metrics:
* `sum(kubelet_volume_stats_used_bytes{persistentvolumeclaim="{pvc}",namespace="{namespace}"}) by (persistentvolumeclaim, namespace)`
* `sum(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim="${pvc}",namespace="${namespace}"}) by (persistentvolumeclaim, namespace)`

**Comment by knrt10** [comment]
Working on this.

**Comment by yolossn** [comment]
@farodin91  Thanks for the suggestion, PVC metrics chart is added.
https://github.com/headlamp-k8s/plugins/pull/28
