### ISSUE TITLE
Flux: Namespace based filtering

### ISSUE THREAD

**Issue by Aubermean** [headlamp-k8s/plugins#80]
Throughout Headlamp, you can filter by namespace. This is respected as you navigate through different views.

It would be really helpful if the Flux plugin had this feature, and even better if it share/tap into any existing namespace filter elsehwere in Headlamp.

<img width="301" alt="image" src="https://github.com/user-attachments/assets/4c406f9a-9cb9-4bb5-afe4-168b31dcb3d4">

#75

**Comment by mgalesloot** [comment]
In addition to this: Users focused on a single namespace (e.g. I want to check the workloads in my namespace) could also be helped with a Flux panel on the Namespace page.

**Comment by Aubermean** [comment]
> In addition to this: Users focused on a single namespace (e.g. I want to check the workloads in my namespace) could also be helped with a Flux panel on the Namespace page.

I am not sure how the plugin system works, but I don't know if the other pages are extensible.

If you have filtered by namespace while in the Flux plugin, clicking on Workloads should still maintain the same namespace. It should be global, as it is already between Events and Workloads etc.
